using System.Collections.Generic;
using UnityEngine;
using frame8.Logic.Misc.Other.Extensions;
using Com.TheFallenGames.OSA.Core;
using Com.TheFallenGames.OSA.CustomParams;
using Com.TheFallenGames.OSA.DataHelpers;
using TMPro;

using Kumu.Kulitan.Social;

// You should modify the namespace to your own or - if you're sure there won't ever be conflicts - remove it altogether
namespace Kumu.Kulitan.UI.OptimizedScrollView
{
	/// <summary>
	/// This class was auto-generated by OSA and was modified to fit usage needs.
	/// </summary>
	public class CommentsScrollView : OSA<BaseParamsWithPrefab, CommentsViewsHolder>
	{
		private List<CommentData> initializedItems = new List<CommentData>();

		// Helper that stores data and notifies the adapter when items count changes
		// Can be iterated and can also have its elements accessed by the [] operator
		public SimpleDataHelper<CommentData> Data { get; set; }

		/// <summary>
		/// Sets the initial items to display.
		/// </summary>
		/// <param name="newItems">list of new items to add</param>
		public void InitializeData(List<CommentData> newItems)
		{
			initializedItems.AddRange(newItems);
			if (Data != null)
			{
				OnDataRetrieved(initializedItems.ToArray());
			}
		}

		/// <summary>
		/// Add a single item at the end of the list.
		/// </summary>
		/// <param name="newItem">the new item to add</param>
		public void AddNewItem(CommentData newItem)
		{
			Data.InsertOneAtEnd(newItem);
		}

		#region OSA implementation
		protected override void Start()
		{
			base.Start();
			Data = new SimpleDataHelper<CommentData>(this);
			OnDataRetrieved(initializedItems.ToArray());
		}

		// This is called initially, as many times as needed to fill the viewport, 
		// and anytime the viewport's size grows, thus allowing more items to be displayed
		// Here you create the "ViewsHolder" instance whose views will be re-used
		// *For the method's full description check the base implementation
		protected override CommentsViewsHolder CreateViewsHolder(int itemIndex)
		{
			var instance = new CommentsViewsHolder();

			// Using this shortcut spares you from:
			// - instantiating the prefab yourself
			// - enabling the instance game object
			// - setting its index 
			// - calling its CollectViews()
			instance.Init(_Params.ItemPrefab, _Params.Content, itemIndex);

			return instance;
		}

		// This is called anytime a previously invisible item become visible, or after it's created, 
		// or when anything that requires a refresh happens
		// Here you bind the data from the model to the item's views
		// *For the method's full description check the base implementation
		protected override void UpdateViewsHolder(CommentsViewsHolder newOrRecycled)
		{
			// In this callback, "newOrRecycled.ItemIndex" is guaranteed to always reflect the
			// index of item that should be represented by this views holder. You'll use this index
			// to retrieve the model from your data set
			CommentData model = Data[newOrRecycled.ItemIndex];

			newOrRecycled.TxtComment.text = model.Comment;
			newOrRecycled.TxtUsername.text = model.User.UserName;
            newOrRecycled.TxtLikesCount.text = model.Likes.Length.ToString();
        }
		#endregion

		
		/// <summary>
        /// Adds a set of items at the end of the list.
        /// Refreshes view.
        /// </summary>
        /// <param name="newItems">array of items to add</param>
		private void OnDataRetrieved(CommentData[] newItems)
		{
			Data.InsertItemsAtEnd(newItems);
		}
	}

	// This class keeps references to an item's views.
	// Your views holder should extend BaseItemViewsHolder for ListViews and CellViewsHolder for GridViews
	public class CommentsViewsHolder : BaseItemViewsHolder
	{
		[SerializeField] private TextMeshProUGUI txtUsername;
		[SerializeField] private TextMeshProUGUI txtComment;
		[SerializeField] private TextMeshProUGUI txtLikesCount;

		public TextMeshProUGUI TxtUsername => txtUsername;
		public TextMeshProUGUI TxtComment => txtComment;
		public TextMeshProUGUI TxtLikesCount => txtLikesCount;

		// Retrieving the views from the item's root GameObject
		public override void CollectViews()
		{
			base.CollectViews();
			root.GetComponentAtPath("txtUsername", out txtUsername);
			root.GetComponentAtPath("txtComment", out txtComment);
			root.GetComponentAtPath("btnHeart/txtCount", out txtLikesCount);
		}		
	}
}
