using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using frame8.Logic.Misc.Other.Extensions;
using Com.TheFallenGames.OSA.Core;
using Com.TheFallenGames.OSA.CustomParams;
using Com.TheFallenGames.OSA.DataHelpers;
using TMPro;

using Kumu.Kulitan.Social;
using System;

// You should modify the namespace to your own or - if you're sure there won't ever be conflicts - remove it altogether
namespace Kumu.Kulitan.UI.OptimizedScrollView
{
	/// <summary>
    /// This class was auto-generated by OSA and was modified to fit usage needs.
    /// </summary>
	public class PostsScrollView : OSA<BaseParamsWithPrefab, PostsViewsHolder>
	{

		[SerializeField] private CommentController commentsController;
		private List<PostData> initializedItems = new List<PostData>();

		// Helper that stores data and notifies the adapter when items count changes
		// Can be iterated and can also have its elements accessed by the [] operator
		public SimpleDataHelper<PostData> Data { get; private set; }

		/// <summary>
		/// Sets the initial items to display.
		/// </summary>
		/// <param name="newItems">list of new items to add</param>
		public void InitializeData(List<PostData> newItems)
		{
			initializedItems.AddRange(newItems);
			if (Data != null)
			{
				OnDataRetrieved(initializedItems.ToArray());
			}
		}

		/// <summary>
		/// Add a single item at the end of the list.
		/// </summary>
		/// <param name="newItem">the new item to add</param>
		public void AddNewItem(PostData newItem)
		{
			Data.InsertOneAtStart(newItem);
		}

		#region OSA implementation
		protected override void Start()
		{
			base.Start();
			Data = new SimpleDataHelper<PostData>(this);
			OnDataRetrieved(initializedItems.ToArray());
		}

		// This is called initially, as many times as needed to fill the viewport, 
		// and anytime the viewport's size grows, thus allowing more items to be displayed
		// Here you create the "ViewsHolder" instance whose views will be re-used
		// *For the method's full description check the base implementation
		protected override PostsViewsHolder CreateViewsHolder(int itemIndex)
		{
			var instance = new PostsViewsHolder();
			instance.Init(_Params.ItemPrefab, _Params.Content, itemIndex);
			instance.OnCommentsPanelShown = () => {
				InitializePostComments(itemIndex);
			};
			return instance;
		}

		// This is called anytime a previously invisible item become visible, or after it's created, 
		// or when anything that requires a refresh happens
		// Here you bind the data from the model to the item's views
		// *For the method's full description check the base implementation
		protected override void UpdateViewsHolder(PostsViewsHolder newOrRecycled)
		{
			// In this callback, "newOrRecycled.ItemIndex" is guaranteed to always reflect the
			// index of item that should be represented by this views holder. You'll use this index
			// to retrieve the model from your data set
			PostData model = Data[newOrRecycled.ItemIndex];

			newOrRecycled.TxtUsername.text = model.User.UserName;
			newOrRecycled.TxtCaption.text = model.Caption;
		}
		#endregion

		/// <summary>
		/// Adds a set of items at the end of the list.
		/// </summary>
		/// <param name="newItems">array of items to add</param>
		private void OnDataRetrieved(PostData[] newItems)
		{
			Data.InsertItemsAtEnd(newItems);
		}

		private void InitializePostComments(int itemIndex)
        {
			var postData = Data[itemIndex];
			commentsController.Initialize(postData.Comments, postData.PostId);
			commentsController.ShowCommentsPanel();
        }
	}

	// This class keeps references to an item's views.
	// Your views holder should extend BaseItemViewsHolder for ListViews and CellViewsHolder for GridViews
	public class PostsViewsHolder : BaseItemViewsHolder
	{
		[SerializeField] private TextMeshProUGUI txtUsername;
		[SerializeField] private TextMeshProUGUI txtCaption;
		[SerializeField] private Button btnComments;

		public TextMeshProUGUI TxtUsername => txtUsername;
		public TextMeshProUGUI TxtCaption => txtCaption;
		public Button BtnComments => btnComments;

		public Action OnCommentsPanelShown { get; set; }

		// Retrieving the views from the item's root GameObject
		public override void CollectViews()
		{
			base.CollectViews();
			root.GetComponentAtPath("Username", out txtUsername);
			root.GetComponentAtPath("Caption", out txtCaption);
			root.GetComponentAtPath("Buttons/btnComments", out btnComments);
			btnComments.onClick.AddListener(ShowCommentPanel);
		}

        public override void OnBeforeDestroy()
        {
            base.OnBeforeDestroy();
			btnComments.onClick.RemoveListener(ShowCommentPanel);
        }

        private void ShowCommentPanel()
		{
			OnCommentsPanelShown?.Invoke();
		}
	}
}
