using System.Collections.Generic;

public static class SpecificMsgIds
{
    public static HashSet<MsgId> DoNotShowLog = new HashSet<MsgId>(
        new MsgId[]
        {
            // Town
            MsgId.TownUnitEnteredNot,
            MsgId.TownUnitLeaveNot,
            MsgId.TownUnitTransformNot,
            MsgId.TownUnitStateNot,
            MsgId.TownChatListNot,
            MsgId.TownChatInvalidTargetNot,
            MsgId.PadStateNot,

            // Battle
            MsgId.BattleSyncNot,
            MsgId.ArrivedZone,
            MsgId.CancelSkillNot,
            MsgId.CutSkillNot,
            MsgId.ReserveSkill,
            MsgId.AiReserveSkillNot,
            MsgId.ClientPauseNot,
            MsgId.AutoPlayNot,
            MsgId.MultiGameSpdNot,
            MsgId.SkipPlayNot,
            MsgId.CompleteResurrectNot,
            MsgId.QuickBattleNot,
            MsgId.TargetingCancelNot,
            MsgId.TargetingCompleteReqAck,
            MsgId.TargetingStartNot,
            MsgId.TargetingStateNot,
        }
    );

    public static HashSet<MsgId> GameOvers = new HashSet<MsgId>(
        new MsgId[]
        {
            MsgId.GameOverNot,
            MsgId.AttrDunGameOverNot,
            MsgId.BossRaidGameOverNot,
            MsgId.ChampPvpGameOverNot,
            MsgId.EventBattleGameOverNot,
            MsgId.FriendlyPvPGameOverNot,
            MsgId.GoodsDunGameOverNot,
            MsgId.GrowthGoodsDunGameOverNot,
            MsgId.GuildTrainingGameOverNot,
            MsgId.OccupationWarBattleGameOverNot,
            MsgId.PvpGameOverNot,
			MsgId.GuildWarBattleGameOverNot,
			MsgId.RoguelikeGameOverNot,
            MsgId.SubStoryBattleGameOverNot,
            MsgId.InfinityWaveGameOverNot,
        }
    );
}

public enum PauseReason
{
    AppPaused = 0,
    Dialog
}

public enum MsgId {

    Unknown = -1,

	////////////////////////////////// Communication to Main Server	
	MainMsgId = 0,					
	MainReqAck = MainMsgId,	
	LoginReqAck,
	RecoverReqAck,
	GoWorldIdxReqAck,
    RoguelikeMoveReqAck,
    TickChangeDataReqAck,
    FishingAutoItemListReqAck,
    LoginNot,
    Login2Not,
    CreateWaitingUI = 200, // <= Wait UI..
	CreateNickReqAck,
	MountHeroReqAck,
	TryMatchReqAck,
	CancelMatchReqAck,	
    StartBattleReqAck,
    StartTownReqAck,
    DeckChangeReqAck,
    RefreshDataReqAck,
    PvpListReqAck,
    PvpStartBattleReqAck,
    PvpBattleListReqAck,
    PvpBattleDetailReqAck,
    PvpRenewReqAck,
    PvpDailyRewardReceiveReqAck,
    PvpTimeRewardReceiveReqAck,
    ClearDBReqAck,
    AdventureSweepReqAck,
    InAppPurchaseCheckReqAck,
    InAppPurchaseRewardReqAck,
    HeroLevelUpReqAck,
    PostListReqAck,
    PostReceiveReqAck,
    PostReceiveAllDeleteReqAck,
    HeroWeaponLvUpReqAck,
    MiniGameClearReqAck,
    HeroGradeUpReqAck,    
    CreateSignatureReqAck,
    ChangeProfileReqAck,
    ChangeNickReqAck,
    ChangeSignatureReqAck,
    WorldItemRewardReqAck,
    CreateHeroReqAck,
    StartChapterReqAck,
    RoguelikeListReqAck,
    RoguelikeStartReqAck,
    RoguelikeGiveUpReqAck,
    RoguelikeSweepReqAck,
    RoguelikeActionPointChargeReqAck,
    RoguelikeBattleStartReqAck,
    RoguelikeGrowthChooseReqAck,
    EquipmentWearReqAck,
    EquipmentLvUpReqAck,
    EquipmentGradeUpReqAck,
    EquipmentLockReqAck,
    GoodsDunListReqAck,
    GrowthGoodsDunListReqAck,
    GoodsDunBattleStartReqAck,
    GoodsDunBattleSweepReqAck,
    GoodsDunTicketChargeReqAck,
    BossRaidListReqAck,
    BossRaidRankReqAck,
    BossRaidRankClearDeckReqAck,
    BossRaidBattleStartReqAck,
    BossRaidChallengeStopReqAck,
    BossRaidChallengeExitReqAck,
    BossRaidSweepReqAck,
    BossRaidSeasonRewardReqAck,
    GachaStartReqAck,
    GachaSelectStartReqAck,
    GachaSelectConfirmReqAck,
    GachaMileageShopBuyReqAck,
    AlchemyStartReqAck,
    ItemDecomposeReqAck,
    EquipmentOptionChangeReqAck,
    StaminaChargeReqAck,
    MissionListReqAck,
    MissionRewardReceiveReqAck,
    MissionRewardReceiveAllReqAck,
    FriendshipGiftReqAck,
    FriendshipStoryReadReqAck,
    HeroSkillLvUpReqAck,
    WriterSkillUnlockReqAck,
    WriterSkillLvUpReqAck,
    WriterSkillDeckChangeReqAck,
    MainStoryWorldSkillActiveReqAck,
    RoguelikeWorldSkillActiveReqAck,
    AccountIntroChangeReqAck,
    FriendListReqAck,
    FriendApplyListReqAck,
    FriendAcceptListReqAck,
    FriendViewReqAck,
    FriendGreetReqAck,
    FriendDeleteReqAck,
    FriendApplyReqAck,
    FriendApplyCancelReqAck,
    FriendAcceptReqAck,
    FriendAcceptAutoReqAck,
    FriendRejectReqAck,
    FriendSearchReqAck,
    FriendSearchInputReqAck,
    GuildListReqAck,
    GuildVisitReqAck,
    GuildJoinApplyReqAck,
    GuildCreateReqAck,
    GuildManageReqAck,
    GuildAcceptListReqAck,
    GuildAcceptReqAck,
    GuildRejectReqAck,
    GuildUserViewReqAck,
    GuildUserWithdrawReqAck,
    GuildUserExpelReqAck,
    GuildUserSubmasterAppointReqAck,
    GuildUserMasterSwapReqAck,
    GuildDisbandReqAck,
    GuildSearchInputReqAck,
    GuildFilterReqAck,
    FarmAddReqAck,
    FarmRemoveReqAck,
    FarmExchangePlantReqAck,
    FarmRemovePetAllReqAck,
    FarmRewardReceiveReqAck,
    FarmRewardReceiveAllReqAck,
    FarmVisitListReqAck,
    FarmVisitReqAck,
    FarmVisitInteractReqAck,
    FarmVisitRandomReqAck,
    AttendRewardReceiveReqAck,
    BirthdayRewardReceiveReqAck,
    SubStoryReadReqAck,
    SubStoryMoveReqAck,
    SubStoryBattleStartReqAck,
    SubStoryBattleSweepReqAck,
    MiniGachaRouletteStartReqAck,
    MainStoryReadReqAck,
    StatsUnitReqAck,
    FishingTutorialRewardReqAck,
    FishingManualStartReqAck,
    FishingManualEndReqAck,
    FishingAutoStartReqAck,
    FishingAutoEndReqAck,
    FishingItemRewardReceiveReqAck,
    FishingExchangeReqAck,
    OccupationWarEnterReqAck,
    OccupationWarBoardViewReqAck,
    OccupationWarBattleStartReqAck,
    OccupationWarBattleSweepReqAck,
    OccupationWarStaminaChargeReqAck,
    OccupationWarBoardRewardReceiveReqAck,
    OccupationWarRankReqAck,
    OccupationWarRankRewardReceiveReqAck,
    OccupationWarPointRewardReceiveReqAck,
    AccountWriterGenderChangeReqAck,
    AccountProfileTownIdChangeReqAck,
    AccountProfileBorderItemIdChangeReqAck,
    MiniGameChallengeEndReqAck,
    MiniGameChallengeRewardReceiveReqAck,
    MiniGameChallengeRewardReceiveAllReqAck,
    ProfilePresetSaveReqAck,
    ProfilePresetLoadReqAck,
    ShopGoodsBuyReqAck,
    InAppPurchaseRewardRestoreReqAck,
    ShopUpdateReqAck,
    SignChangeReqAck,
    SignWithdrawReqAck,
    AutoItemDecomposeSettingReqAck,
    CouponRewardReceiveReqAck,
    SeasonPassRewardReceiveReqAck,
    HeroWeaponGradeUpReqAck,
    EquipmentOptionChangeTempReqAck,
    ArchiveActiveReqAck,
    ArchiveAddBuffActiveReqAck,
    ArchiveResetReqAck,
    MainStoryChapterClearRewardReceiveReqAck,
    ArenaRankReqAck,
    HeroInterestReqAck,
    RelationLvUpReqAck,
    MissionNewComebackFinalRewardReceiveReqAck,
    MainStoryHardPlayChargeReqAck,
    LobbyUnitSetReqAck,
    WriterSkillBonusActiveReqAck,
    WriterSkillResetReqAck,
    ArenaTicketChargeReqAck,
    FishingManualStartActionReqAck,
    FishingManualEndActionReqAck,
    PrizeExchangeDrawReqAck,
    PrizeExchangeNextBoxReqAck,
    ChoiceBoxSelectReqAck,
    AttrDunSelectReqAck,
    AttrDunHeroRecoverReqAck,
    AttrDunBattleStartReqAck,
	AttrDunBattleSweepReqAck,
	AttrDunRankingReqAck,
    ChampPvpListReqAck,
    ChampPvpBattleStartReqAck,
    ChampPvpBattleRecordReqAck,
    ChampPvpBattleRecordDetailReqAck,
    ChampPvpRenewReqAck,
    ChampPvpDailyRewardReceiveReqAck,
    ChampPvpTimeRewardReceiveReqAck,
    ChampPvpRankReqAck,
    EventBattleStartReqAck,
	GachaRepeatRewardReceiveReqAck,

	AgreementChangeNotAck,                  //알람 동의 저장
    CollabCouponListReqAck,
    CollabCouponRewardReceiveReqAck,
    ChampArenaTicketChargeReqAck,
	GuildTrainingBattleStartReqAck,
	GuildTrainingCreateBattleReqAck,
	GuildTrainingRankingReqAck,
	DiceBoardGameRollReqAck,
    SubStoryDifficultyChangeReqAck,
	NewComebackGiftRewardReceiveReqAck,
	AnniversaryGiftRewardReceiveReqAck,
	ItemUseReqAck,
    SurveySelectReqAck,
    SurveyRewardReqAck,
	ReplayUploadListReqAck,
	ReplayUploadReqAck,
	ReplayRawReqAck,
	ReplayThumbupReqAck,
	ReplayUploadDeleteReqAck,
    GuildWarListReqAck,
    GuildWarRankReqAck,
    GuildWarBattlefieldListReqAck,
    GuildWarBattleRecordReqAck,
    GuildWarBattleRecordDetailReqAck,
    GuildWarLastRewardReceiveReqAck,
    GuildWarBattleStartReqAck,
	GuildItemRequestListReqAck,
	GuildItemRequestReqAck,
	GuildDonateReqAck,
	GuildItemRequestPumpUpReqAck,
    RuneStoneAttachReqAck,
    RuneStoneDetachReqAck,
    RuneStoneAttachGradeUpReqAck,
    RuneStoneDetachGradeUpReqAck,
    OccWarComPingChangeReqAck,
    OccWarComMsgChangeReqAck,
    BingoPlayReqAck,
	UnitPieceGroupSelectReqAck,
    GuildWarSiegeWeaponBuyReqAck,
    GuildWarBattleRefreshReqAck,
    InfinityWaveBattleStartReqAck,
    InfinityWaveBattleSweepReqAck,
    InfinityWaveRankingReqAck,
    InfinityWaveUpgradeLvUpReqAck,
    InfinityWaveNextBattleStartReqAck,
    AdAddCountReqAck,
    InfinityWaveRankingRewardReqAck,



    MainS2C_Not = 1000,
	MatchSuccessNot,
	BattleResultNot,
    FriendlyPvPNot,
    FriendlyPvPAcceptNot,    
    ChapterClearNot,
    RoguelikeAddItemNot,
    RoguelikeAddGrowthNot,
    RoguelikeHpCureNot,
    RoguelikeClearNot,
    TutorialNot,
    MissionClearNot,
    GuildUserExpelNot,
    GuildAcceptNot,
    OccupationWarExitNot,
    OccupationWarChangeNot,

    MainC2S_Not = 2000,
    AgreementChangeNot,

	////////////////////////////////// Communication to Battle Server	
	BattleMsgId = 3000,
	BattleReqAck = BattleMsgId,	
	EnterBattleReqAck,
    TargetingCompleteReqAck,
    BattleSnapshot,
    EnterBotReqAck,

    BattleS2CNot = 3100,
    BattleSyncNot,
    GameOverNot,
    CancelSkillNot,
    DialogStartNot,
    DialogEndNot,
    TargetingStartNot,
    AiReserveSkillNot,
    PvpGameOverNot,
    TargetingStateNot,
    FriendlyPvPGameOverNot,
    AllUserEnteredNot,
    RoguelikeGameOverNot,
    GoodsDunGameOverNot,
    GrowthGoodsDunGameOverNot,
    BossRaidGameOverNot,
    QuickBattleNot,
    SubStoryBattleGameOverNot,
    OccupationWarBattleGameOverNot,
    AttrDunGameOverNot,
    ChampPvpGameOverNot,
    EventBattleGameOverNot,
    GuildTrainingGameOverNot,
    GuildWarBattleGameOverNot,
    InfinityWaveGameOverNot,

    BattleC2SNot = 3200,	
    ArrivedZone,
    ReserveSkill,
    ClientPauseNot,
    MultiGameSpdNot,
    AutoPlayNot,
    SkipPlayNot,
    CompleteResurrectNot,
    TargetingCancelNot,
    CancelReserveSkillNot,
    CutSkillNot,
    InfinityWaveAbilitySelectReqAck,

    ////////////////////////////////// Communication to Town Server
    TownMsgId = 4000,
    TownReqAck = TownMsgId,
    EnterTownReqAck,
    CreateTownWaitingUI, 
    TownChannelsReqAck,
    FriendlyPvPReqAck,
    FriendlyPvPAcceptReqAck,
    FriendlyPvPRejectReq,

    TownS2CNot = 4100,
    TownUnitEnteredNot,
    TownUnitLeaveNot,
    TownUnitTransformNot,
    TownUnitStateNot,
    TownChatListNot,
    TownChatInvalidTargetNot,
    FriendlyPvPRejectNot,
    BroadcastTownArenaTopRankNot,

    TownC2SNot = 4200,
    PadStateNot,
    TownChatNot,
    TownMyUnitStateNot,    

    ////////////////////////////////// Communication to Chat Server
    ChatMsgId = 5000,
	ChatReqAck = ChatMsgId,
	EnterChatReqAck,

    ChatS2C_Not = 5100,
	BroadcastChatNot,
    GuildChatEnterNot,
    GuildChatChangeNot,
    OccupationWarChatChangeNot,
    ChatBawlingNot,
    ChatGuildAttendRewardNot,
    OccWarComChangeNot,

    ChatC2S_Not = 5200,
	ChatNot,

    ////////////////////////////////// Communication Sever 2 Server
    S2SMsgId = 9000,	
	ServerIdentityNot,
	UserCountNot,
	CreateBattleReqAck,
	PvpCreateBattleReqAck,
    NotSupportedGameNot,
	UserEndGameNot,
    FriendlyPvPReadyBattleReqAck,
    FriendlyPvPCreateBattleReqAck,
    RoguelikeCreateBattleReqAck,
    GoodsDunCreateBattleReqAck,
    BossRaidCreateBattleReqAck,
    SubStoryCreateBattleReqAck,
    OccupationWarCreateBattleReqAck,
    AttrDunCreateBattleReqAck,
    ChampPvpCreateBattleReqAck,
    EventCreateBattleReqAck,
    TownServerCountNot,
    ReportNewAccUidsNot,
    GuildWarCreateBattleReqAck,
    InfinityWaveBattleCreateReqAck,

    ////////////////////////////////// System Msg Id
    Error = 9999,
    ReportNetUid,

#if DEV || LOCAL || QA
    ////////////////////////////////// Cheat
    CheatGameOver = 30000,
    CheatGameSpd,
    CheatChangeHeroLvGrade,
    CheatOccupy,
    CheatUnitDie,
    CheatAddMagic,
    CheatAddMagicById,
    CheatMobBonusRates,
    PacketTest,
#endif
}
